[[permission]]
identifier = "allow-app-commands"
description = "Allow all app commands"
commands.allow = [
    "get_watched_folders",
    "add_watched_folder",
    "remove_watched_folder",
    "search_directories",
    "set_quality",
    "get_quality",
    "get_compression_history",
    "clear_compression_history",
    "delete_original_images",
    "recompress",
    "compress_files"
]
